// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_data from "./routes/api/data.ts";
import * as $index from "./routes/index.tsx";
import * as $receive_id_ from "./routes/receive/[id].tsx";
import * as $send from "./routes/send.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $receive from "./islands/receive.tsx";
import * as $send_1 from "./islands/send.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/data.ts": $api_data,
    "./routes/index.tsx": $index,
    "./routes/receive/[id].tsx": $receive_id_,
    "./routes/send.tsx": $send,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/receive.tsx": $receive,
    "./islands/send.tsx": $send_1,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
